server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: mysecretkey
  expiration: 3600000
