server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
kafka:
  topic:
    order-events: order-events
