server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shipmentdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
kafka:
  topic:
    shipment-events: shipment-events
